version: '3.7'
services:
  mangas-service:
    env_file:
      - .env
    build:
      context: ./android-springboot-backend
      dockerfile: Dockerfile
    hostname: mangas-backend
    container_name: mangas-backend
    image: mangas-backend
    restart: always
    ports:
    - 8080:8080
    depends_on:
      - postgres
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${JDBC_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${JDBC_DATABASE_PASSWORD}
      - POSTGRES_DB=${JDBC_DATABASE_DB}
    volumes:
      - postgres-data:/var/lib/posgresql/data
volumes:
  postgres-data:
